var angebote = [
	{	
		name:	"Patient:innenservice (116117) und Ärzt:innen-Suche der Kassenärztlichen Bundesvereinigung (KBV)",
		description:	"In einer Psychotherapie kannst du mit einer speziell dafür ausgebildeten Person (psychologische oder ärztliche Psychotherapeut:innen) über deine Probleme oder Sorgen sprechen. Diese Behandlung kann dir helfen, wenn du merkst, dass du deine täglichen Aufgaben z. B. im Haushalt oder bei der Arbeit nicht mehr schaffst. Wenn du überlegst, eine Psychotherapie zu machen, kannst du über die Website der KBV (Kassenärztliche Bundesvereinigung) herausfinden, wo es Psychotherapeut:innen in deiner Nähe gibt. Über die Termin-Servicestellen kannst du telefonisch unter der Nummer 116117 einen Termin für eine psychotherapeutische Sprechstunde vereinbaren.",
		link:	"https://www.kbv.de/html/arztsuche.php",
		cost:	2,
		location:	3,
		hilfsangeboteKlinisch:	1,
		hilfsangeboteSubklinisch:	0,
		information:	1,
		praevention:	0,
		psychoedukation:	0,
		einzelangebot:	0,
		website_PDF:	1,
		app:	0,
		hotline:	1,
		vermittlung:	1,
		beratung:	0,
		austausch:	0,
		contact:	"offline",
	},
	{	
		name:	"HelloBetter",
		description:	"Hier findest du Online-Trainings zu folgenden Themen: Corona, Stressfrei, Schlafen, Chronische Schmerzen, Depression, Panik, Weniger trinken, Vaginismus, Diabetes und Depression – auf Wunsch mit Begleitung durch Psycholog:innen und Psychotherapeut:innen.",
		link:	"https://hellobetter.de/",
		cost:	4,
		location:	1,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	1,
		information:	0,
		praevention:	1,
		psychoedukation:	1,
		einzelangebot:	1,
		website_PDF:	1,
		app:	0,
		hotline:	1,
		vermittlung:	0,
		beratung:	0,
		austausch:	1,
		contact:	"beides",


	},
	{	
		name:	"Psychenet: Netz Psychische Gesundheit",
		description:	"Diese Seite informiert dich über Beschwerden, Ursachen und Behandlungsmöglichkeiten einzelner psychischer Erkrankungen im Erwachsenenalter. Zusätzlich findest du Antworten auf allgemeine Fragen wie: Was ist psychische Gesundheit? Was ist eigentlich eine Diagnose? Wie können psychische Erkrankungen behandelt werden? Was ist Psychotherapie? Die Autor:innen stützen sich auf aktuelle wissenschaftliche Erkenntnisse und die Erfahrung von Psychotherapeut:innen und Ärzt:innen.",
		link:	"https://www.psychenet.de/de/",
		cost:	1,
		location:	3,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	0,
		information:	1,
		praevention:	0,
		psychoedukation:	1,
		einzelangebot:	0,
		website_PDF:	1,
		app:	0,
		hotline:	0,
		vermittlung:	1,
		beratung:	1,
		austausch:	0,
		contact:	"online",
	},
	{
		name:	"Psychenet: Netz Psychische Gesundheit",
		description:	"Diese Seite informiert dich über Beschwerden, Ursachen und Behandlungsmöglichkeiten einzelner psychischer Erkrankungen im Erwachsenenalter. Zusätzlich findest du Antworten auf allgemeine Fragen wie: Was ist psychische Gesundheit? Was ist eigentlich eine Diagnose? Wie können psychische Erkrankungen behandelt werden? Was ist Psychotherapie? Die Autor:innen stützen sich auf aktuelle wissenschaftliche Erkenntnisse und die Erfahrung von Psychotherapeut:innen und Ärzt:innen.",
		link:	"https://www.psychenet.de/de/",
		cost:	1,
		location:	3,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	0,
		information:	1,
		praevention:	0,
		psychoedukation:	1,
		einzelangebot:	0,
		website_PDF:	1,
		app:	0,
		hotline:	0,
		vermittlung:	1,
		beratung:	1,
		austausch:	0,
		contact:	"online",
		
	},
	{
		name:	"MyMoodpath",
		description:	"Wenn du mit Depressionen oder Ängsten zu kämpfen hast, unterstützt dich die App Moodpath auf deinem Weg zu emotionalem Wohlbefinden.",
		link:	"https://mymoodpath.com/de/",
		cost:	4,
		location:	1,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	1,
		information:	0,
		praevention:	0,
		psychoedukation:	1,
		einzelangebot:	0,
		website_PDF:	0,
		app:	1,
		hotline:	0,
		vermittlung:	0,
		beratung:	0,
		austausch:	0,
		contact:	"online",
	
	
		
	},
	{
		name:	"Telefonseelsorge",
		description:	"Wenn du dich belastet fühlst und nach Hilfe suchst, eignen sich Telefonhotlines als erste Anlaufstelle. Ohne deinen Namen oder deinen Wohnort nennen zu müssen, kannst du mit einer Person unverbindlich und geheim über deine Probleme sprechen. Die Expert:innen am Telefon beraten dich, was du in deiner Situation tun kannst. Zudem geben sie dir Informationen zu Angeboten, die dir helfen können. Die Telefonseelsorge ist jeden Tag und rund um die Uhr unter 0800 1110111 oder 0800 1110222 erreichbar.",
		link:	"https://www.telefonseelsorge.de",
		cost:	1,
		location:	1,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	1,
		information:	0,
		praevention:	0,
		psychoedukation:	0,
		einzelangebot:	0,
		website_PDF:	1,
		app:	0,
		hotline:	1,
		vermittlung:	0,
		beratung:	1,
		austausch:	0,
		contact:	"beides",
		
	},
	{
		name:	"Berliner Krisendienst",
		description:	"Wenn du dich sehr stark belastet fühlst und/oder in einer seelischen Krise befindest, kannst du dich an den Berliner Krisendienst wenden. Dieser ist für alle Menschen in Berlin rund um die Uhr telefonisch und persönlich erreichbar. Auf der Website findest du die Telefonnummer für deinen Berliner Stadtbezirk.",
		link:	"https://www.berliner-krisendienst.de/",
		cost:	1,
		location:	2,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	1,
		information:	0,
		praevention:	0,
		psychoedukation:	0,
		einzelangebot:	0,
		website_PDF:	0,
		app:	0,
		hotline:	1,
		vermittlung:	0,
		beratung:	1,
		austausch:	0,
		contact:	"offline";

	},
	{
		name:	"Online Beratung Caritas",
		description:	"Online, anonym und sicher kannst du hier Hilfe für deine Probleme finden. Ohne deinen Namen anzugeben, kannst du Fragen stellen und erhältst eine Antwort von Fachleuten. Wenn du lieber persönlich mit jemanden sprechen möchtest, kannst du auf der Seite auch nach Einrichtungen in deiner Nähe suchen.",
		link:	"https://www.caritas.de/hilfeundberatung/",
		cost:	1,
		location:	1,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	1,
		information:	1,
		praevention:	0,
		psychoedukation:	0,
		einzelangebot:	0,
		website_PDF:	1,
		app:	0,
		hotline:	0,
		vermittlung:	1,
		beratung:	1,
		austausch:	0,
		contact:	"beides";
		
	},
	{
		name:	"7mind",
		description:	"Die App 7Mind bietet dir einen ein­fachen Ein­stieg in die Medi­ta­tion. Sie versorgt dich mit individuellen Tipps und kurzen Meditationen, die sich jeder­zeit ein­schie­ben lassen. Der 7Mind-Medi­ta­ti­ons­guide leitet dich Schritt für Schritt durch deine ersten Medi­ta­tio­nen – oder hilft dir, deine Praxis zu erwei­tern. Im Grund­la­gen­kurs lernst du in 7 x 7 Minu­ten ein­fa­che Medi­ta­ti­ons­tech­ni­ken. Mit Kursen wie Schlaf, Stress, Kon­zen­tra­tion oder Glück kannst du die Themen ver­tie­fen, die dir am wich­tigs­ten sind. Per­sön­li­che Emp­feh­lun­gen helfen dir, auch auf Dauer dabei zu blei­ben.",
		link:	"https://www.7mind.de",
		cost:	4,
		location:	1,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	0,
		information:	0,
		praevention:	1,
		psychoedukation:	0,
		einzelangebot:	1,
		website_PDF:	1,
		app:	1,
		hotline:	0,
		vermittlung:	0,
		beratung:	0,
		austausch:	0,
		contact:	"online",
			
	},
	{
		name:	"deprexis",
		description:	"Deprexis ist ein Online-Therapieprogramm für leichte bis mittelschwere Depressionen, welches dich während deiner Therapie mit Übungen und Dialogen unterstützen kann. Für eine Nutzung ist eine ärztliche oder therapeutische Bestätigung notwendig.",
		link:	"https://de.deprexis.com/",
		cost:	2,
		location:	1,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	1,
		information:	0,
		praevention:	0,
		psychoedukation:	0,
		einzelangebot:	1,
		website_PDF:	1,
		app:	1,
		hotline:	0,
		vermittlung:	0,
		beratung:	1,
		austausch:	0,
		contact:	"online",
			
	},
	{
		name:	"Psychosozialer und psychiatrischer Krisendienst der Region Hannover",
		description:	"Unter der Nummer 0511 30 03 34 70 erhältst du Unterstützung, wenn du dich sehr stark belastet fühlst und/oder in einer seelischen Krise befindest. Der Krisendienst ist freitags von 15:00 bis 20:00 Uhr, sowie am Wochenende und feiertags von 12:00 bis 20:00 Uhr für Menschen in der Region Hannover erreichbar.",
		link:	"https://www.hannover.de/Leben-in-der-Region-Hannover/Gesundheit/Beratungsstellen/Fachdienst-Sozialpsychiatrischer-Dienst/Psychosozialer-Psychiatrischer-Krisendienst-PPKD-in-der-Region-Hannover",
		cost:	1,
		location:	2,
		hilfsangeboteKlinisch:	0,
		hilfsangeboteSubklinisch:	1,
		information:	0,
		praevention:	0,
		psychoedukation:	0,
		einzelangebot:	0,
		website_PDF:	1,
		app:	0,
		hotline:	1,
		vermittlung:	0,
		beratung:	0,
		austausch:	0,
		contact:	"offline",
	
	},
	
];
